In [1]:
import numpy as np
import pandas as pd
import ast

business_pd_Dat = pd.read_csv('cleaned_bus_pd_Dat.csv', low_memory=False)

In [4]:
len(business_pd_Dat)

141914

In [3]:
all_attributes_rows = pd.read_csv('all_attributes_rowswithgaragestreetlotvaletccprice_rangeNaNto1_march_4th_450pm.csv', low_memory=False)

In [5]:
len(all_attributes_rows)

141914

In [6]:
all_merge = pd.merge(business_pd_Dat, all_attributes_rows, left_index=True, right_index=True)

In [7]:
len(all_merge)

141914

In [8]:
all_merge.head()

,Unnamed: 0,Unnamed: 0.1,address,attributes,business_id,categories,city,hours,is_open,latitude,...,RestaurantsTakeOut,Smoking,WheelchairAccessible,WiFi,garage,street,lot,valet,AcceptsCreditCards,price ranges NaN to 1
0,0,0,2818 E Camino Acequia Drive,{'GoodForKids': 'False'},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,NaN,0,33.522143,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
1,1,1,"10110 Johnston Rd, Ste 15","{'GoodForKids': 'True', 'NoiseLevel': ""u'avera...",gnKjwL_1w79qoiV3IC_xQQ,"Sushi Bars, Restaurants, Japanese",Charlotte,"{'Monday': '17:30-21:30', 'Wednesday': '17:30-...",1,35.092564,...,True,NaN,NaN,u'no',False,False,True,False,True,2.0
2,2,2,"15655 W Roosevelt St, Ste 237",NaN,xvX2CttrVhyG2z1dFg_0xw,"Insurance, Financial Services",Goodyear,"{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ...",1,33.455613,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
3,3,3,"4209 Stuart Andrew Blvd, Ste F","{'BusinessAcceptsBitcoin': 'False', 'ByAppoint...",HhyxOkGAM07SRYtlQ4wMFQ,"Plumbing, Shopping, Local Services, Home Servi...",Charlotte,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,35.190012,...,NaN,NaN,NaN,NaN,False,False,False,False,True,1.0
4,4,4,"4545 E Tropicana Rd Ste 8, Tropicana","{'RestaurantsPriceRange2': '3', 'GoodForKids':...",gbQN7vr_caG_A1ugSmGhWg,"Hair Salons, Hair Stylists, Barbers, Men's Hai...",Las Vegas,"{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'...",1,36.099872,...,NaN,NaN,NaN,NaN,False,False,False,False,True,3.0

In [13]:
dropped = all_merge.drop(['Unnamed: 0'],axis = 1)

In [20]:
dropped.head()

,Unnamed: 0.1,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,...,RestaurantsTakeOut,Smoking,WheelchairAccessible,WiFi,garage,street,lot,valet,AcceptsCreditCards,price ranges NaN to 1
0,0,2818 E Camino Acequia Drive,{'GoodForKids': 'False'},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,NaN,0,33.522143,-112.018481,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
1,1,"10110 Johnston Rd, Ste 15","{'GoodForKids': 'True', 'NoiseLevel': ""u'avera...",gnKjwL_1w79qoiV3IC_xQQ,"Sushi Bars, Restaurants, Japanese",Charlotte,"{'Monday': '17:30-21:30', 'Wednesday': '17:30-...",1,35.092564,-80.859132,...,True,NaN,NaN,u'no',False,False,True,False,True,2.0
2,2,"15655 W Roosevelt St, Ste 237",NaN,xvX2CttrVhyG2z1dFg_0xw,"Insurance, Financial Services",Goodyear,"{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ...",1,33.455613,-112.395596,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
3,3,"4209 Stuart Andrew Blvd, Ste F","{'BusinessAcceptsBitcoin': 'False', 'ByAppoint...",HhyxOkGAM07SRYtlQ4wMFQ,"Plumbing, Shopping, Local Services, Home Servi...",Charlotte,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,35.190012,-80.887223,...,NaN,NaN,NaN,NaN,False,False,False,False,True,1.0
4,4,"4545 E Tropicana Rd Ste 8, Tropicana","{'RestaurantsPriceRange2': '3', 'GoodForKids':...",gbQN7vr_caG_A1ugSmGhWg,"Hair Salons, Hair Stylists, Barbers, Men's Hai...",Las Vegas,"{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'...",1,36.099872,-115.074574,...,NaN,NaN,NaN,NaN,False,False,False,False,True,3.0

In [24]:
dropped.columns = dropped.columns.str.replace('Unnamed: 0.1', 'index_final')

In [26]:
dropped.head()

,index_final,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,...,RestaurantsTakeOut,Smoking,WheelchairAccessible,WiFi,garage,street,lot,valet,AcceptsCreditCards,price ranges NaN to 1
0,0,2818 E Camino Acequia Drive,{'GoodForKids': 'False'},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,NaN,0,33.522143,-112.018481,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
1,1,"10110 Johnston Rd, Ste 15","{'GoodForKids': 'True', 'NoiseLevel': ""u'avera...",gnKjwL_1w79qoiV3IC_xQQ,"Sushi Bars, Restaurants, Japanese",Charlotte,"{'Monday': '17:30-21:30', 'Wednesday': '17:30-...",1,35.092564,-80.859132,...,True,NaN,NaN,u'no',False,False,True,False,True,2.0
2,2,"15655 W Roosevelt St, Ste 237",NaN,xvX2CttrVhyG2z1dFg_0xw,"Insurance, Financial Services",Goodyear,"{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ...",1,33.455613,-112.395596,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
3,3,"4209 Stuart Andrew Blvd, Ste F","{'BusinessAcceptsBitcoin': 'False', 'ByAppoint...",HhyxOkGAM07SRYtlQ4wMFQ,"Plumbing, Shopping, Local Services, Home Servi...",Charlotte,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,35.190012,-80.887223,...,NaN,NaN,NaN,NaN,False,False,False,False,True,1.0
4,4,"4545 E Tropicana Rd Ste 8, Tropicana","{'RestaurantsPriceRange2': '3', 'GoodForKids':...",gbQN7vr_caG_A1ugSmGhWg,"Hair Salons, Hair Stylists, Barbers, Men's Hai...",Las Vegas,"{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'...",1,36.099872,-115.074574,...,NaN,NaN,NaN,NaN,False,False,False,False,True,3.0

In [28]:
final_all_merge = dropped.set_index("index_final")

In [29]:
final_all_merge.head()

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,...,RestaurantsTakeOut,Smoking,WheelchairAccessible,WiFi,garage,street,lot,valet,AcceptsCreditCards,price ranges NaN to 1
index_final,,,,,,,,,,,,,,,,,,,,,
0,2818 E Camino Acequia Drive,{'GoodForKids': 'False'},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,NaN,0,33.522143,-112.018481,Arizona Biltmore Golf Club,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
1,"10110 Johnston Rd, Ste 15","{'GoodForKids': 'True', 'NoiseLevel': ""u'avera...",gnKjwL_1w79qoiV3IC_xQQ,"Sushi Bars, Restaurants, Japanese",Charlotte,"{'Monday': '17:30-21:30', 'Wednesday': '17:30-...",1,35.092564,-80.859132,Musashi Japanese Restaurant,...,True,NaN,NaN,u'no',False,False,True,False,True,2.0
2,"15655 W Roosevelt St, Ste 237",NaN,xvX2CttrVhyG2z1dFg_0xw,"Insurance, Financial Services",Goodyear,"{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ...",1,33.455613,-112.395596,Farmers Insurance - Paul Lorenz,...,NaN,NaN,NaN,NaN,False,False,False,False,False,1.0
3,"4209 Stuart Andrew Blvd, Ste F","{'BusinessAcceptsBitcoin': 'False', 'ByAppoint...",HhyxOkGAM07SRYtlQ4wMFQ,"Plumbing, Shopping, Local Services, Home Servi...",Charlotte,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,35.190012,-80.887223,Queen City Plumbing,...,NaN,NaN,NaN,NaN,False,False,False,False,True,1.0
4,"4545 E Tropicana Rd Ste 8, Tropicana","{'RestaurantsPriceRange2': '3', 'GoodForKids':...",gbQN7vr_caG_A1ugSmGhWg,"Hair Salons, Hair Stylists, Barbers, Men's Hai...",Las Vegas,"{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'...",1,36.099872,-115.074574,Supercuts,...,NaN,NaN,NaN,NaN,False,False,False,False,True,3.0

In [ ]:
##now copy and past eall the algorithms to it

In [39]:
star_ratings_all = final_all_merge['stars']

In [42]:
review_count_all = final_all_merge['review_count']

In [31]:
logistic_x_features_all = final_all_merge[['valet','garage','street','lot','AcceptsCreditCards','review_count','price ranges NaN to 1']]

In [34]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [35]:
from sklearn.linear_model import LogisticRegression
my_logistic_regression = LogisticRegression()

In [36]:
def convert(v):
    updated = []
    for i in v:
        if i > 3:
            updated.append(1)
        else:
            updated.append(0)
    return updated

In [37]:
binary_from_threshold_all = convert(star_ratings_all)

In [40]:
star_ratings_reshape_all = np.array(star_ratings_all).reshape(-1,1)

In [43]:
review_count_reshape_all = np.array(review_count_all).reshape(-1,1)

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
scaler = MinMaxScaler()

In [48]:
rescaled_features = scaler.fit_transform(logistic_x_features_all)

In [45]:
##before normilizing
from sklearn.model_selection import cross_val_score
Log_reg_scores_all = cross_val_score(my_logistic_regression, logistic_x_features_all, binary_from_threshold_all , cv =5, scoring='accuracy').mean()
Log_reg_scores_all

0.6740913511713222

In [50]:
##normilizng isnt really making a difference
from sklearn.model_selection import cross_val_score
Log_reg_scores_all_normalized = cross_val_score(my_logistic_regression, rescaled_features, binary_from_threshold_all , cv =5, scoring='accuracy').mean()
Log_reg_scores_all_normalized

0.6740913511713222